---
- name: LIDO-WITHDRAWALS-AUTOMATION | Create Dockerfile
  template:
    src: '../templates/Dockerfile.j2'
    dest: '{{ lido_withdrawals_automation_dockerfile }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0644

- name: LIDO-WITHDRAWALS-AUTOMATION | Create compose file
  template:
    src: '../templates/docker-compose.yml.j2'
    dest: '{{ lido_withdrawals_automation_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0644

- name: LIDO-WITHDRAWALS-AUTOMATION | Create container
  shell:
    chdir: '{{lido_withdrawals_automation_service_path}}'
    cmd: docker compose up

- name: LIDO-WITHDRAWALS-AUTOMATION | Restart Ejector container
  docker_compose:
    project_src: '{{ ejector_service_path }}'
    pull: true
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate }}'